<div class="h1">QR decomposition of matrices</div>
<p class="author">(Szabó Sándor)</p>
<p class="date">2018. április</p>

<p class="abstract">Abstract</p>
<p class="normal">We investigate the $QR$ decomposition of a matrix, its realization in Python and some applications.</p><br />

# Table of Contents
 <p><div class="lev1 toc-item"><a href="#Definitions" data-toc-modified-id="Definitions-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Definitions</a></div><div class="lev1 toc-item"><a href="#Theorems" data-toc-modified-id="Theorems-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Theorems</a></div><div class="lev1 toc-item"><a href="#Proof-of-Theorems-1-and-2" data-toc-modified-id="Proof-of-Theorems-1-and-2-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Proof of Theorems 1 and 2</a></div><div class="lev1 toc-item"><a href="#QR-factorization-algorithms" data-toc-modified-id="QR-factorization-algorithms-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>QR-factorization algorithms</a></div><div class="lev2 toc-item"><a href="#Gram-Schmidt-orthogonalization" data-toc-modified-id="Gram-Schmidt-orthogonalization-41"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Gram-Schmidt orthogonalization</a></div><div class="lev2 toc-item"><a href="#Givens-rotations" data-toc-modified-id="Givens-rotations-42"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Givens rotations</a></div><div class="lev2 toc-item"><a href="#Householder-reflections" data-toc-modified-id="Householder-reflections-43"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Householder reflections</a></div><div class="lev1 toc-item"><a href="#Realization-in-Python" data-toc-modified-id="Realization-in-Python-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Realization in Python</a></div><div class="lev1 toc-item"><a href="#Applications" data-toc-modified-id="Applications-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Applications</a></div><div class="lev2 toc-item"><a href="#Calculation-of-determinant" data-toc-modified-id="Calculation-of-determinant-61"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Calculation of determinant</a></div><div class="lev2 toc-item"><a href="#Least-Square-solution-of-linear-system" data-toc-modified-id="Least-Square-solution-of-linear-system-62"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Least Square solution of linear system</a></div><div class="lev1 toc-item"><a href="#Bibliography" data-toc-modified-id="Bibliography-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Bibliography</a></div>

# Definitions 

<div class="definition"> 
<p class="normal">Definition 1. In linear algebra a $QR$ decomposition of a matrix is a decomposition of a matrix $A$ into a product $A=QR$ of an orthogonal matrix $Q$ and an upper triangular matrix $R$.</p>
</div>

# Theorems

<div class="theorem">
<p class="normal">Theorem 1. If $A\in\mathcal{M}_n$ is an invertable matrix, then there exists a unique pair of orthogonal matrix $Q\in\mathcal{M}_n$ and upper triangular matrix $R\in\mathcal{M}_n$ with positive diagonal entries such that 
$$
A=QR.
$$
</p>
</div>

<div class="theorem">
<p class="normal">Theorem 2. If $A\in\mathcal{M}_{m\times n}$, $m\geq n$, then there exists a matrix $Q\in\mathcal{M}_{m\times n}$ with orthonormal columns and an upper triangular matrix $R\in\mathcal{M}_n$ such that
$$
A=QR.
$$
</p>
</div>

# Proof of Theorems 1 and 2

<div class="proof">
<p class="normal">Proof. <br />
Uniqueness: Suppose that $A=Q_1R_1=Q_2R_2$, where $Q_1,Q_2$ are orthogonal and $R_1,R_2$
are upper triangular with positive diagonal entries. Then
$$
M:=R_1R_2^{\,-1}=Q_1^*Q_2.
$$
Since $M$ is upper triangular and orthogonal, it must be diagonal. 
The diagonal entries of $M$ are positive (because the upper triangular matrices $R_1$ and $R_2^{\,-1}$ 
have positive diagonal entries) and of modulus one. Hence $M=I$, and consequently 
$$
R_1=R_2, \,\,\, Q_1=Q_2.
$$
Existence: (later)
</p>
</div>

# QR-factorization algorithms

## Gram-Schmidt orthogonalization

In [17]:
%%html
<iframe 
width="600" height="365" 
src="https://www.youtube.com/embed/jiKSNKPwBS0" 
frameborder="0" allow="autoplay; encrypted-media" 
allowfullscreen>
</iframe>

In [15]:
#from IPython.lib.display import YouTubeVideo
#YouTubeVideo('jiKSNKPwBS0')

In [16]:
#from IPython.display import HTML
## Youtube
#HTML('<iframe width="600" height="365" src="https://www.youtube.com/embed/jiKSNKPwBS0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>')

## Givens rotations

## Householder reflections

# Realization in Python

In [2]:
%matplotlib inline

In [3]:
import matplotlib.pyplot as plt
import numpy as np
from numpy.linalg import qr
import sympy as sp
from sympy import *

In [4]:
from IPython.display import HTML,Latex, display
init_printing(use_unicode=True) # nice output

In [47]:
A = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]])
print('A= \n', A)

A= 
 [[ 12 -51   4]
 [  6 167 -68]
 [ -4  24 -41]]


In [45]:
Q, R = qr(A, 'complete')
print('Q= \n', Q)
print('R= \n', R)
err = A - np.dot(Q, R)
print('A-QR= \n', err)
max_err = np.max(np.abs(err))
print('max error= ', max_err)

Q= 
 [[-0.85714286  0.39428571  0.33142857]
 [-0.42857143 -0.90285714 -0.03428571]
 [ 0.28571429 -0.17142857  0.94285714]]
R= 
 [[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]
A-QR= 
 [[  0.00000000e+00   1.42108547e-14  -1.77635684e-15]
 [  0.00000000e+00  -2.84217094e-14   1.42108547e-14]
 [  8.88178420e-16   0.00000000e+00   0.00000000e+00]]
max error=  2.84217094304e-14


# Applications

## Calculation of determinant

<p class="normal">
If $A=QR$ then
\begin{align*}
\det(A) &=\det(Q)\det(R) \\
        &=\det(R) \\
        &=\prod_{i}r_{ii}
\end{align*}
</p>

<div class="definition"> 
<p class="normal">Definition 1. In linear algebra a $QR$ decomposition of a matrix is a decomposition of a matrix $A$ into a product $A=QR$ of an orthogonal matrix $Q$ and an upper triangular matrix $R$.</p>
</div>

## Least Square solution of linear system

<p class="normal">
Many times the linear system 
$$
A\boldsymbol{x}=\boldsymbol{b}
$$
has no solution. In this case we may want to minimize the distance $\boldsymbol{r}$ between $A\boldsymbol{x}$ and $\boldsymbol{b}$. If we use euclidean distance 
we can write
\begin{align*}
\Vert \boldsymbol{r} \Vert^2 &=\Vert \boldsymbol{b}-A\boldsymbol{x}\Vert^2 \\
&=\Vert \boldsymbol{b}-QR\boldsymbol{x}\Vert^2 \\
&=\Vert Q^*\boldsymbol{b}-(Q^*Q)R\boldsymbol{x}\Vert^2 \,\,\, \text{because }Q\text{ is orthogonal}  \\
&=\Vert Q^*\boldsymbol{b}-R\boldsymbol{x}\Vert^2    
\,\,\,\text{because }Q^*Q=I  \\
&=\Vert \boldsymbol{c}-R\boldsymbol{x}\Vert^2
\,\,\,\text{where } \boldsymbol{c}=Q^*\boldsymbol{b}=
\left[
\begin{array}{rr}
    \boldsymbol{c}_1  \\
    \boldsymbol{c}_2  
\end{array}
\right] \\
&=\Vert \boldsymbol{c}_1-R\boldsymbol{x}\Vert^2
+\Vert \boldsymbol{c}_2\Vert^2 \\
&=\Vert \boldsymbol{c}_2\Vert^2\,\,\,\text{if we choose }\boldsymbol{x} \text{ such that }R\boldsymbol{x}=\boldsymbol{c}_1.
\end{align*}
</p>

# Bibliography

<p class="normal">
[1] Wikipedia, QR decomposition. 
<a href="https://en.wikipedia.org/wiki/QR_decomposition">Homepage</a>
</p>

In [6]:
from IPython.core.display import HTML
#def css_styling():
#    styles = open("HomeWorks/css/hw.css", "r").read()
#    return HTML("<style>"+styles+"</style>")
#css_styling()

In [7]:
from IPython.display import HTML
import urllib2
HTML(urllib2.urlopen('https://github.com/wesszabo/numerikus-szamitasok/blob/master/HomeWorks/css/hw.css').read())

ModuleNotFoundError: No module named 'urllib2'

In [11]:
from IPython.display import HTML
import requests
url = 'https://github.com/wesszabo/numerikus-szamitasok/blob/master/HomeWorks/css/hw.css'
r = requests.get(url)
print(r.content)

b'\n\n\n\n\n\n<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n  <link rel="dns-prefetch" href="https://assets-cdn.github.com">\n  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">\n  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">\n  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">\n  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">\n  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">\n  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">\n\n\n\n  <link crossorigin="anonymous" media="all" rel="stylesheet" href="https://assets-cdn.github.com/assets/frameworks-29f21e31d44fd2c6858f04860799bc74.css" />\n  <link crossorigin="anonymous" media="all" rel="stylesheet" href="https://assets-cdn.github.com/assets/github-08c0695b372c4d0fadbe37f9e2300ed2.css" />\n  \n  \n  <link crossorigin="anonymous" media="all" rel="stylesheet" href="htt

In [15]:
%%html
<script src="https://cdn.rawgit.com/parente/4c3e6936d0d7a46fd071/raw/65b816fb9bdd3c28b4ddf3af602bfd6015486383/code_toggle.js"></script>

In [ ]:
wget.download('url', file_name)